### PR TITLE
Twig 2.7 support without deprecated. Used spaceless filter

### PR DESCRIPTION
**Pull request by maximmandrik**
Text deprecated:
https://github.com/twigphp/Twig/blob/1a05a525bbf320c50a105723c481df8156947eb8/lib/Twig/Node/Spaceless.php

### CODE REVIEW

**Comment by maximmandrik** [comment]
What is the error when passing the test "continuous-integration / travis-ci / pr", I can not see the details.

Sorry for such a pull reguest, this is my first.

**Comment by phansys** [comment]
Hi @maximmandrik. Thank you so much for your first contribution.
There seems to be an issue with the Travis routing, which shows the the message
>We couldn't find the repository 
KnpLabs/KnpMenu".

I'm able to access the build results by navigating from the project's home at Travis: https://travis-ci.org/KnpLabs. This is part of the build results based on your changes:
<details>
<summary>Test output</summary>

```
$ php ./vendor/bin/simple-phpunit
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
Testing KnpMenu Test Suite
...SSSSS.......................................................  63 / 279 ( 22%)
............................................................... 126 / 279 ( 45%)
....................SSSS....................................... 189 / 279 ( 67%)
...SSSS....FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFF................. 252 / 279 ( 90%)
...........................                                     279 / 279 (100%)
Time: 923 ms, Memory: 30.00MB
There were 34 failures:
1) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderOrderedList
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ol><li class="first last"><span>About</span><ol class="menu_level_1"><li class="first last"><span>foobar</span></li></ol></li></ol>'
+'<ol><li class="first last"><span>About</span><ol class="menu_level_1"><li class="first last"><span>foobar</span></li></ol></li></ol>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/TwigRendererTest.php:30
2) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderEmptyRoot
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-''
+'
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:42
3) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderRootWithAttributes
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul class="test_class"><li class="first last"><span>c1</span></li></ul>'
+'<ul class="test_class"><li class="first last"><span>c1</span></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:51
4) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderEncodedAttributes
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul title="encode &quot; me &gt;"><li class="first last"><span>c1</span></li></ul>'
+'<ul title="encode &quot; me &gt;"><li class="first last"><span>c1</span></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:60
5) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderLink
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul><li class="first last"><a href="/about">About</a></li></ul>'
+'<ul><li class="first last"><a href="/about">About</a></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:69
6) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderLinkWithAttributes
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul><li class="first last"><a href="/about" title="About page">About</a></li></ul>'
+'<ul><li class="first last"><a href="/about" title="About page">About</a></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:78
7) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderLinkWithEmptyAttributes
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul><li class="first last"><a href="/about" title="">About</a></li></ul>'
+'<ul><li class="first last"><a href="/about" title="">About</a></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:90
8) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderLinkWithSpecialAttributes
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul><li class="first last"><a href="/about" title="title">About</a></li></ul>'
+'<ul><li class="first last"><a href="/about" title="title">About</a></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:99
9) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderChildrenWithAttributes
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul><li class="first last"><span>About</span><ul title="About page" class="menu_level_1"><li class="first last"><span>Us</span></li></ul></li></ul>'
+'<ul><li class="first last"><span>About</span><ul title="About page" class="menu_level_1"><li class="first last"><span>Us</span></li></ul></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:110
10) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderChildrenWithEmptyAttributes
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul><li class="first last"><span>About</span><ul title="" class="menu_level_1"><li class="first last"><span>Us</span></li></ul></li></ul>'
+'<ul><li class="first last"><span>About</span><ul title="" class="menu_level_1"><li class="first last"><span>Us</span></li></ul></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:123
11) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderChildrenWithSpecialAttributes
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul><li class="first last"><span>About</span><ul title="title" class="menu_level_1"><li class="first last"><span>Us</span></li></ul></li></ul>'
+'<ul><li class="first last"><span>About</span><ul title="title" class="menu_level_1"><li class="first last"><span>Us</span></li></ul></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:134
12) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderLabelWithAttributes
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul><li class="first last"><span title="About page">About</span></li></ul>'
+'<ul><li class="first last"><span title="About page">About</span></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:143
13) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderLabelWithEmptyAttributes
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul><li class="first last"><span title="">About</span></li></ul>'
+'<ul><li class="first last"><span title="">About</span></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:152
14) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderLabelWithSpecialAttributes
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul><li class="first last"><span title="title">About</span></li></ul>'
+'<ul><li class="first last"><span title="title">About</span></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:161
15) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderWeirdLink
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul><li class="first last"><a href="http://en.wikipedia.org/wiki/%22Weird_Al%22_Yankovic?v1=1&amp;v2=2">About</a></li></ul>'
+'<ul><li class="first last"><a href="http://en.wikipedia.org/wiki/%22Weird_Al%22_Yankovic?v1=1&amp;v2=2">About</a></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:170
16) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderEscapedLabel
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul><li class="first"><span>Encode &quot; me</span></li><li><span>Encode &quot; me again</span></li><li class="last"><span>Encode &quot; me too</span></li></ul>'
+'<ul><li class="first"><span>Encode &quot; me</span></li><li><span>Encode &quot; me again</span></li><li class="last"><span>Encode &quot; me too</span></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:181
17) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderSafeLabel
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul><li class="first"><span>Encode &quot; me</span></li><li><span>Encode " me again</span></li><li class="last"><span>Encode &quot; me too</span></li></ul>'
+'<ul><li class="first"><span>Encode &quot; me</span></li><li><span>Encode " me again</span></li><li class="last"><span>Encode &quot; me too</span></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:192
18) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderWholeMenu
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul class="root"><li class="first"><span>Parent 1</span><ul class="menu_level_1"><li class="first"><span>Child 1</span></li><li><span>Child 2</span></li><li class="last"><span>Child 3</span></li></ul></li><li class="last"><span>Parent 2</span><ul class="menu_level_1"><li class="first last"><span>Child 4</span><ul class="menu_level_2"><li class="first last"><span>Grandchild 1</span></li></ul></li></ul></li></ul>'
+'<ul class="root"><li class="first"><span>Parent 1</span><ul class="menu_level_1"><li class="first"><span>Child 1</span></li><li><span>Child 2</span></li><li class="last"><span>Child 3</span></li></ul></li><li class="last"><span>Parent 2</span><ul class="menu_level_1"><li class="first last"><span>Child 4</span><ul class="menu_level_2"><li class="first last"><span>Grandchild 1</span></li></ul></li></ul></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:198
19) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderWithClassAndTitle
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul class="root"><li class="first"><span>Parent 1</span><ul class="menu_level_1"><li class="first"><span>Child 1</span></li><li><span>Child 2</span></li><li class="last"><span>Child 3</span></li></ul></li><li class="parent2_class last" title="parent2 title"><span>Parent 2</span><ul class="menu_level_1"><li class="first last"><span>Child 4</span><ul class="menu_level_2"><li class="first last"><span>Grandchild 1</span></li></ul></li></ul></li></ul>'
+'<ul class="root"><li class="first"><span>Parent 1</span><ul class="menu_level_1"><li class="first"><span>Child 1</span></li><li><span>Child 2</span></li><li class="last"><span>Child 3</span></li></ul></li><li class="parent2_class last" title="parent2 title"><span>Parent 2</span><ul class="menu_level_1"><li class="first last"><span>Child 4</span><ul class="menu_level_2"><li class="first last"><span>Grandchild 1</span></li></ul></li></ul></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:206
20) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderWithCurrentItem
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul class="root"><li class="current_ancestor first"><span>Parent 1</span><ul class="menu_level_1"><li class="first"><span>Child 1</span></li><li class="current"><span>Child 2</span></li><li class="last"><span>Child 3</span></li></ul></li><li class="last"><span>Parent 2</span><ul class="menu_level_1"><li class="first last"><span>Child 4</span><ul class="menu_level_2"><li class="first last"><span>Grandchild 1</span></li></ul></li></ul></li></ul>'
+'<ul class="root"><li class="current_ancestor first"><span>Parent 1</span><ul class="menu_level_1"><li class="first"><span>Child 1</span></li><li class="current"><span>Child 2</span></li><li class="last"><span>Child 3</span></li></ul></li><li class="last"><span>Parent 2</span><ul class="menu_level_1"><li class="first last"><span>Child 4</span><ul class="menu_level_2"><li class="first last"><span>Grandchild 1</span></li></ul></li></ul></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:213
21) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderWithCurrentItemAsLink
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul><li class="current first last"><a href="/about">About</a></li></ul>'
+'<ul><li class="current first last"><a href="/about">About</a></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:223
22) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderWithCurrentItemNotAsLink
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul><li class="current first last"><span>About</span></li></ul>'
+'<ul><li class="current first last"><span>About</span></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:233
23) Knp\Menu\Tests\Renderer\TwigRendererTest::testRenderSubMenuPortionWithClassAndTitle
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul class="parent2_class" title="parent2 title"><li class="first last"><span>Child 4</span><ul class="menu_level_2"><li class="first last"><span>Grandchild 1</span></li></ul></li></ul>'
+'<ul class="parent2_class" title="parent2 title"><li class="first last"><span>Child 4</span><ul class="menu_level_2"><li class="first last"><span>Grandchild 1</span></li></ul></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:240
24) Knp\Menu\Tests\Renderer\TwigRendererTest::testDoNotShowChildrenRendersNothing
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-''
+'
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:247
25) Knp\Menu\Tests\Renderer\TwigRendererTest::testDoNotShowChildChildrenRendersPartialMenu
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul class="root"><li class="first"><span>Parent 1</span></li><li class="last"><span>Parent 2</span><ul class="menu_level_1"><li class="first last"><span>Child 4</span><ul class="menu_level_2"><li class="first last"><span>Grandchild 1</span></li></ul></li></ul></li></ul>'
+'<ul class="root"><li class="first"><span>Parent 1</span></li><li class="last"><span>Parent 2</span><ul class="menu_level_1"><li class="first last"><span>Child 4</span><ul class="menu_level_2"><li class="first last"><span>Grandchild 1</span></li></ul></li></ul></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:254
26) Knp\Menu\Tests\Renderer\TwigRendererTest::testDoNotShowChildRendersPartialMenu
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul class="root"><li class="first last"><span>Parent 2</span><ul class="menu_level_1"><li class="first last"><span>Child 4</span><ul class="menu_level_2"><li class="first last"><span>Grandchild 1</span></li></ul></li></ul></li></ul>'
+'<ul class="root"><li class="first last"><span>Parent 2</span><ul class="menu_level_1"><li class="first last"><span>Child 4</span><ul class="menu_level_2"><li class="first last"><span>Grandchild 1</span></li></ul></li></ul></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:261
27) Knp\Menu\Tests\Renderer\TwigRendererTest::testDepth0
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-''
+'
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:267
28) Knp\Menu\Tests\Renderer\TwigRendererTest::testDepth1
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul class="root"><li class="first"><span>Parent 1</span></li><li class="last"><span>Parent 2</span></li></ul>'
+'<ul class="root"><li class="first"><span>Parent 1</span></li><li class="last"><span>Parent 2</span></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:273
29) Knp\Menu\Tests\Renderer\TwigRendererTest::testDepth2
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul class="root"><li class="first"><span>Parent 1</span><ul class="menu_level_1"><li class="first"><span>Child 1</span></li><li><span>Child 2</span></li><li class="last"><span>Child 3</span></li></ul></li><li class="last"><span>Parent 2</span><ul class="menu_level_1"><li class="first last"><span>Child 4</span></li></ul></li></ul>'
+'<ul class="root"><li class="first"><span>Parent 1</span><ul class="menu_level_1"><li class="first"><span>Child 1</span></li><li><span>Child 2</span></li><li class="last"><span>Child 3</span></li></ul></li><li class="last"><span>Parent 2</span><ul class="menu_level_1"><li class="first last"><span>Child 4</span></li></ul></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:279
30) Knp\Menu\Tests\Renderer\TwigRendererTest::testDepth2WithNotShowChildChildren
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul class="root"><li class="first"><span>Parent 1</span></li><li class="last"><span>Parent 2</span><ul class="menu_level_1"><li class="first last"><span>Child 4</span></li></ul></li></ul>'
+'<ul class="root"><li class="first"><span>Parent 1</span></li><li class="last"><span>Parent 2</span><ul class="menu_level_1"><li class="first last"><span>Child 4</span></li></ul></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:286
31) Knp\Menu\Tests\Renderer\TwigRendererTest::testMatchingDepth0
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul class="root"><li class="first"><span>Parent 1</span></li><li class="last"><span>Parent 2</span></li></ul>'
+'<ul class="root"><li class="first"><span>Parent 1</span></li><li class="last"><span>Parent 2</span></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:299
32) Knp\Menu\Tests\Renderer\TwigRendererTest::testMatchingDepth1
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul class="root"><li class="current_ancestor first"><span>Parent 1</span></li><li class="last"><span>Parent 2</span></li></ul>'
+'<ul class="root"><li class="current_ancestor first"><span>Parent 1</span></li><li class="last"><span>Parent 2</span></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:306
33) Knp\Menu\Tests\Renderer\TwigRendererTest::testMatchingDepth2
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul class="root"><li class="first"><span>Parent 1</span></li><li class="last"><span>Parent 2</span></li></ul>'
+'<ul class="root"><li class="first"><span>Parent 1</span></li><li class="last"><span>Parent 2</span></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:313
34) Knp\Menu\Tests\Renderer\TwigRendererTest::testLeafAndBranchRendering
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<ul class="root"><li class="first branch"><span>Parent 1</span><ul class="menu_level_1"><li class="first leaf"><span>Child 1</span></li><li class="leaf"><span>Child 2</span></li><li class="last leaf"><span>Child 3</span></li></ul></li><li class="last branch"><span>Parent 2</span><ul class="menu_level_1"><li class="first last leaf"><span>Child 4</span></li></ul></li></ul>'
+'<ul class="root"><li class="first branch"><span>Parent 1</span><ul class="menu_level_1"><li class="first leaf"><span>Child 1</span></li><li class="leaf"><span>Child 2</span></li><li class="last leaf"><span>Child 3</span></li></ul></li><li class="last branch"><span>Parent 2</span><ul class="menu_level_1"><li class="first last leaf"><span>Child 4</span></li></ul></li></ul>
+'
/home/travis/build/KnpLabs/KnpMenu/tests/Knp/Menu/Tests/Renderer/AbstractRendererTest.php:320
FAILURES!
Tests: 279, Assertions: 467, Failures: 34, Skipped: 13.
Legacy deprecation notices (9)
The command "php ./vendor/bin/simple-phpunit" exited with 1.
cache.2
store build cache
0.00s2.41schanges detected, packing new archive
uploading PR.301/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--php-5.6.tgz
cache uploaded
Done. Your build exited with 1.
```
</details>

BTW, please check #300, which is already open targeting the same issue you're trying to fix here.

**Comment by garak** [comment]
Closed in favor of #300 
Thanks anyway @maximmandrik

**Comment by garak** [comment]
Closing since #300 is merged.
Thanks anyway @maximmandrik

**Pull request closed without merging**
