### PR TITLE
do not ship docs

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by Nek-** [comment]
Hello,

Thanks for your contribution. Any argument of why we should not ship the documentation?

**Comment by OskarStark** [comment]
Hey @Nek- 👋 

A release is meant to be used in production.
If a developer needs it, he can visit the repo, the website (if it has one) or execute composer install with `--prefer-source` option.

**Comment by Nek-** [comment]
AFAIK it impacts the zip download. In this case it would be better to get the doc ? (I get that nobody should use this button but well, it still exists)

Also if you want to remove docs why not removing `README.md` and `CHANGELOG.md` ?

**Comment by OskarStark** [comment]
We are removing the .md files too for sonata project

**Comment by Nek-** [comment]
I don't feel it ok for changelog file (which can really be useful in many cases). But I would like to see the README ignored as it's part of documentation to me. Feel free to update your PR in that way.

Thanks again for your contribution. :+1:

**Comment by OskarStark** [comment]
done

**Comment by craue** [comment]
The folder is actually named `doc`. 😈

**Comment by craue** [comment]
...and the file `README.markdown`.

**Comment by Nek-** [comment]
Genious.

**Comment by OskarStark** [comment]
I created a PR

**Pull request merged**
