### PR TITLE
composer: use PSR-4 autoloading

### PR DESCRIPTION
**Pull request by TomasVotruba**
PSR-0 is deprecated

### CODE REVIEW

**Comment by dbu** [comment]
+1
but i think you need to also move all files from src/Knp/Menu to src/ to make this work.

**Comment by stof** [comment]
@dbu nope. this config works perfectly fine

**Comment by TomasVotruba** [comment]
@dbu This would actually really complicate history in git.

Also tests, that make use of composer autoloading, are passing.

**Comment by dbu** [comment]
a right. but the point of PSR-4 was to eliminate unnecessary deep folders... with `git mv` the history should not be lost afaik. am i wrong with that?

**Comment by stof** [comment]
The PSR-0 autoloading is not deprecated in Composer itself, and our code is compatible with PSR-4. I'm not sure which one is the most efficient in composer (in prod, you should use the optimized autoloader anyway)

@dbu we would still have conflicts in all existing PRs though.

**Comment by dbu** [comment]
well, this works so i merged.

i am not sure about conflicts - git tends to be quite clever, if the move is not seen as a remove and add, it could even understand what was going on. but then i am not religious about paths, so lets leave it and move on :-)

**Comment by TomasVotruba** [comment]
@dbu Thanks!

**Comment by dbu** [comment]
thanks to you!
i am trying to bring down the list of open pull requests and issues and
move things forward with knp menu.

**Comment by stof** [comment]
@dbu git is quite clever about resolving merges for renames when performing the conflict resolution on the machine where the rename was done. It is less clever when it relies only on the data pushed to the remote (or maybe github is less clever at it than git, I don't know)

**Pull request merged**
