### PR TITLE
Remove castings

### PR DESCRIPTION
**Pull request by u01jmg3**
- `ItemInterface::setLabelAttribute(string $name, $value)`
- `ItemInterface::setLinkAttribute(string $name, $value)`

### CODE REVIEW

**Comment by u01jmg3** [comment]
@GeertDD: hopefully this is what you wanted

**Comment by u01jmg3** [comment]
@garak: hopefully this is what you wanted

**Comment by garak** [comment]
Not sure why, but tests are failing

**Comment by u01jmg3** [comment]
Would help if I did a proper job! Tests now pass

**Pull request merged**
