### PR TITLE
travis: PHP 7.0 nightly added + few improvements

### PR DESCRIPTION
**Pull request by TomasVotruba**
- force container based builds
- make phpunit run explicit

### CODE REVIEW

**Comment by stof** [comment]
please also enable the directory cache for ``$HOME/.composer/cache/files`` so that we have a change to reuse cached downloads between builds

**Comment by TomasVotruba** [comment]
@stof Done

**Comment by dbu** [comment]
great, thanks!

**Comment by TomasVotruba** [comment]
@dbu :+1:

**Pull request merged**
