### PR TITLE
Change "Symfony2" references

### PR DESCRIPTION
**Pull request by GawainLynch**
Please don't hesitate to reject this if there is a good reason that it is still the way/version it was … but "hype train" :wink:

### CODE REVIEW

**Comment by stof** [comment]
Well, I'm not sure about this change.

http://symfony-reloaded.org/ was the Symfony 2 website during early development (before the switch to https://symfony.com). Changing the menu item to say `Symfony 4` > `Coming soon` while using the old link looks weird (and the example would then have to be updated in 2 weeks to say `4.1` as 4 would be there already...).

I see 2 options here:

- keep the existing example, with the reference to the old domain, but I don't think most people would understand the reference (most people joined the community long after the symfony-reloaded.org domain stopped being used, except for a redirection which still exists)
- change the example entirely, in favor of an example which does not become outdated after each Symfony release

We might go for the second option

**Comment by GawainLynch** [comment]
Yeah, I did wonder about the link … it does have the big PR banner down the bottom, but still.

While agreeing with all points, what I would note though, is that we've found it wrong to assume how long people have been around for, or the depth of knowledge they might have about the project and its history  … e.g. plenty of people still get confused about Bolt's :koala: references, and what does issue 1555 mean something :wink: 

Ancillary to your option 2, if you want to close this please don't think it would be taken confrontationally here … otherwise, I'll have a think over coming days and try to come up with a better option. But family celebrations in Paris have me missing release.

**Comment by stof** [comment]
In any case, even if we were merging the new example as is, the PR is broken: it changes the menu definition, but does not update the output in the next code block.

The fact that many people don't know the history on the early Symfony 2 development is the reason why I tend to think that option 2 would be better: remove the joke related to Symfony 2 coming soon, and give a generic example instead.

I would be happy if you could change the example that way. And no pressure about the delay. We have no deadline to update the readme.

**Comment by GawainLynch** [comment]
I had a bit of time before catching the train, so I thought I'd have another attempt. This time I've been a bit more thorough.

So I have opted for `s/Symfony2/Symfony/`, `s/Coming soon/Happy Awesome Developers/` (a hat-tip to Knp) and `s/symfony-reloaded.org/symfony.com/`.

Easy to tweak, happy to do so if if you have better ideas or wishes.

**Comment by stof** [comment]
thanks

**Pull request merged**
