### PR TITLE
Readme: simplify install

### PR DESCRIPTION
**Pull request by TomasVotruba**
Composer pick last allowed version by default

### CODE REVIEW

**Comment by Nek-** [comment]
Could be wrong in some terms without quotes. (for instance in mine :-) )

**Comment by TomasVotruba** [comment]
@Nek- Interesting :) What term do you use?

Otherwise ok?

**Comment by Nek-** [comment]
My bad I just tested (was not on my computer). It's working, the version not working was with the `:` char.

Then when you do that the version will be `^2.0`. And as we follow [semver](http://semver.org/) the version `2.1` will be cool for everybody. So the best version tag in composer.json is `~2.0`.

**Comment by TomasVotruba** [comment]
The point is this is future proof, both for editors and users. In case version 3 will be out, all places where this is used, have to be changed.

Also there are some BC breaks between 1, 2 and 3, which might be related to PHP or some other package version etc. This change would put all this deciding work to composer, who manages it the best.

Do you see any advantages?

**Comment by dbu** [comment]
:+1:

**Comment by TomasVotruba** [comment]
@dbu :+1:

**Comment by WouterJ** [comment]
:-1: On this PR.

If a 3.0 major version is released, the README of 2.0 will lead to an installation of the 3.0 major version (as it'll just pick the latest stable version). This introduces lots of confusion, as people try to implement 2.0 things from the docs with their installed 3.0 version.

**Comment by TomasVotruba** [comment]
@WouterJ In that case, if you want to do this properly, you'd have to update Readme for every minor version, because Readme of 2.0 will lead to code 2.1, Readme of 2.1 will lead to code of 2.2 etc. And not using ~2.x, but 2.2, which is vendor locking and doesn't allow using never versions. It's over-optimization in my opinion.

This is common practice and composer's convention. Nothing special.

**Comment by WouterJ** [comment]
Yes, you would always need to update it each minor version, not that much work.

Omitting the version number is usefull when you for instance say: You also need to install package X if you want to use this feature: `composer require package/x`
For the installation guide of a package, it is important that the user installs a correct version.

In the Symfony docs, we've readded the versions because of this.

**Comment by TomasVotruba** [comment]
Symfony is great collection of packages, where are BC breaks among minor versions, as expected in such a big chunk code.

This would be in favor of making BC breaks in minor version in small packages, which is not necessary, since it's around 30 classes in here.

I would say you need to use specific version, when you need to use outdated code to be compatible with your legacy app. Otherwise, when using package for the first time, you want to use last version possible.

**Pull request merged**
