### PR TITLE
Output children if ancestor is current (or child is)

### LINKED ISSUE #84: How to display children, if parent is current.
Hi,

Loving the library here, stopped me porting my Symfony 1.4 plugin over so thanks!

One thing I can't work out though, is if you define a few menu items, and some of them have children, how can you render the children of only the current menu item?

``` php

$factory = new MenuFactory();
$menu = $factory->createItem('My menu');
$menu->addChild('Home', array('uri' => '/'));
$menu->addChild('Comments');

$menu['Comments']->setUri('/comments');
$menu['Comments']->addChild('My comments', array('uri' => '/my_comments'));

```

I only want My Comments (and it's siblings ul) to be rendered if Comments is the active menu item.

Any ideas?

### PR DESCRIPTION
**Pull request by catchamonkey**
Adds a property and methods to add ability to only output children of 
 a menu item, if the item itself, or the ancestor is 'current'.

Closes #84

### CODE REVIEW

**Comment by thedamnedrhino** [comment]
Is this feature implemented in any way currently?

**Comment by pguso** [comment]
I came to this pull request over google and searched for a other solution...knp implemented it:

the attribute is called: **ancestorClass** (https://github.com/KnpLabs/KnpMenu/blob/master/doc/01-Basic-Menus.markdown)

You can use it like this:

    {{ knp_menu_render('MyBundle:Builder:mainMenu', {'currentClass': 'active', 'branch_class': 'sub js-submenu', 'ancestorClass': 'active'}) }}

**Comment by garak** [comment]
It looks like this PR is not needed anymore.
@catchamonkey can you confirm?

**Comment by catchamonkey** [comment]
@garak We ran off the branch in my form since the PR never went anywhere.
Will happily close the PR, pretty sure it's not in use anymore anyway.

Thanks.

**Pull request closed without merging**
