### PR TITLE
Improve Readme with Documentation TOC

### PR DESCRIPTION
**Pull request by shakaran**
Add table of content to documentation for easy and direct access with links and anchors to every main section in documentation.

it should make easy to begginers access to all the knowledge.

### CODE REVIEW

**Comment by garak** [comment]
This looks a bit overkill to me

**Comment by shakaran** [comment]
> This looks a bit overkill to me

Will help a lot with SEO too about search problems and easy linked to every section. My next PR would be link between chapters (next and previous). Others projects has the same way and it is very powerful for starters

**Comment by stof** [comment]
If this is maintained manually (which is the case right now, as the PR does not include any script generating it), it will become outdated over time.

**Comment by shakaran** [comment]
> If this is maintained manually (which is the case right now, as the PR does not include any script generating it), it will become outdated over time.

It could be maintained through stdin via files and generated directly from the docs files, see this project for reference:

https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/README.md

For now, I would prefer at least some documentation linked than nothing. The docs also didn't changed a lot in the last years (maybe this change in future), but we can do always new PR or automatize in future.

**Comment by garak** [comment]
I'm closing this, since two maintainers out of three are against it.
Thank you anyway for your proposal @shakaran

**Pull request closed without merging**
